title: "Abdul Aziz Mandal"
name: "Abdul Aziz Mandal"
description: "Master’s graduate in Chemistry | Molecular Dynamics | Computational Chemistry"
email: "abdulazizcaluniv@gmail.com"
github_username: "AzizSimX"

url: "https://AzizSimX.github.io"
baseurl: ""

markdown: kramdown
theme: jekyll-theme-minimal

author:
  name   : "Abdul Aziz Mandal"
  avatar : "https://github.com/AzizSimX.png"
  bio    : "Master’s in Chemistry, specializing in Physical Chemistry. Passionate about MD simulations, protein aggregation, and drug discovery."
  location: "Kolkata, India"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:abdulazizcaluniv@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/AzizSimX"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/"
    - label: "Download CV"
      icon: "fas fa-file-pdf"
#      url: "/assets/docs/CV_Abdul_Aziz_Mandal.pdf"

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
  - title: "Blog"
    url: /blog/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

